<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <DebugType>embedded</DebugType>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
        </RestoreAdditionalProjectSources>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HarmonyX" Version="2.9.0" />
        <PackageReference Include="PolySharp" Version="1.13.1" />
        <PackageReference Include="BepInEx.Core" Version="5.4.21" />
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.PluginInfoProps" Version="1.1.0" />
        <PackageReference Include="UnityEngine.Modules" Version="2019.4.36" IncludeAssets="compile" />
        <PackageReference Include="Subnautica.GameLibs" Version="82304.0.0-r.0" ExcludeAssets="all"/>
        <PackageReference Include="Jbeast.Subnautica.Unsealed" Version="82304.0.0-r.0" />
        <PackageReference Include="Subnautica.Nautilus" Version="1.0.0-pre.51" PrivateAssets="all">
            <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <Target Name="LoadGameDirs" 
            AfterTargets="SetupTargetFiles" 
            Condition="'$(Configuration)' == 'Debug' And Exists('game-dirs')">
        <ReadLinesFromFile File="game-dirs">
            <Output TaskParameter="Lines" ItemName="GameDirs"/>
        </ReadLinesFromFile>
    </Target>
    
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PathMap>$(MSBuildProjectDirectory)=./</PathMap>
    </PropertyGroup>

    <Target Name="SetupTargetFiles" 
            AfterTargets="PostBuildEvent">
        <ItemGroup>
            <TargetFiles Include="$(TargetPath)"/>
            <TargetFiles Include="LICENSE"/>
            <TargetFiles Include="dist-readme.md" Link="README.md"/>
        </ItemGroup>
    </Target>

    <Target Name="CopyToPluginsDir" 
            AfterTargets="LoadGameDirs" 
            Condition="'$(Configuration)' == 'Debug' And Exists('game-dirs')" 
            Inputs="@(GameDirs);@(TargetFiles)" 
            Outputs="%(GameDirs.Identity)/BepInEx/plugins/$(ProjectName)/**">
        <PropertyGroup>
            <GameDir>%(GameDirs.Identity)</GameDir>
        </PropertyGroup>
        <Copy SourceFiles="@(TargetFiles)" DestinationFolder="$(GameDir)/BepInEx/plugins/$(ProjectName)/%(RecursiveDir)"/>
        <WriteLinesToFile File="$(GameDir)/BepInEx/plugins/$(ProjectName)/load-order.txt"/>
        <MakeDir Directories="$(GameDir)/BepInEx/plugins/$(ProjectName)/patches"/>
    </Target>
    
    <Target Name="ZipDist" AfterTargets="SetupTargetFiles" Condition="'$(Configuration)' == 'Release'">
        <RemoveDir Directories="target/dist"/>
        <Copy SourceFiles="@(TargetFiles)" DestinationFolder="target/dist/$(ProjectName)/%(RecursiveDir)"/>
        <WriteLinesToFile File="target/dist/$(ProjectName)/load-order.txt"/>
        <MakeDir Directories="target/dist/$(ProjectName)/patches"/>
        <ZipDirectory SourceDirectory="target/dist" DestinationFile="target/$(ProjectName).zip" Overwrite="true"/>
        <RemoveDir Directories="target/dist"/>
    </Target>
</Project>
