name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build
      run: msbuild -property:Configuration=Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: target/dist
