name: Mono

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete
    - name: Build
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-target
        path: build/target/*
